parameters:
  open_weather_map_api_key: '%env(OPEN_WEATHER_MAP_API_KEY)%'
  open_weather_map_api_url: '%env(OPEN_WEATHER_MAP_API_URL)%'
  bored_api_url: '%env(BORED_API_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Infrastructure\Api\OpenWeatherMapApi:
    arguments: [ '%open_weather_map_api_key%', '%open_weather_map_api_url%' ]

  App\Application\Weather\Controller\WeatherController:
    tags:
      - { name: 'controller.service_arguments' }

  App\Infrastructure\Api\BoredApi:
    arguments: [ '%bored_api_url%' ]

  App\Application\Activity\Controller\ActivityController:
    tags:
      - { name: 'controller.service_arguments' }